all: 	run1
run1: 	server2.o
	gcc -o run1 server2.o
server.o:	server.c
	gcc -c server2.c
clean: 
	rm run1 server2.o

all: 	run3
run3: 	client2.o
	gcc -o run3 client2.o -lpthread
client.o:	client.c
	gcc -c client2.c -lpthread
clean: 
	rm run3 client2.o


