all: 	run1
run1: 	server2.o
	gcc -o run1 server2.o
server.o:	server.c
	gcc -c server2.c
clean: 
	rm run1 server2.o

all: 	run3
run3: 	client3.o
	gcc -o run3 client3.o -lpthread
client.o:	client3.c
	gcc -c client3.c -lpthread
clean: 
	rm run3 client3.o


